export const getters = {
  DATASETS: 'DATASETS',
  LOADING: 'LOADING',
  SELECTED_DATASETS: 'SELECTED_DATASETS',
};

export const mutations = {
  SET_DATASETS: 'SET_DATASETS',
  SET_LOADING: 'SET_LOADING',
  SET_SELECTED_DATASETS: 'SET_SELECTED_DATASETS',
};

export const actions = {
  FETCH_DATASETS: 'FETCH_DATASETS',
  SELECT_DATASETS: 'SELECT_DATASETS',
};
