version: "3"

services:
  # Flask Application
  server:
    build: "./server"
    ports:
      - "5000:8080"
    depends_on:
      - redis
      - mysql
    networks:
      - backend
    restart: always
  # Datastore for validating API auth tokens
  redis:
    image: redis:3.2-alpine
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    networks:
      - backend
    volumes:
      - ./db/data/redis:/data
    restart: always
  # Database
  mysql:
    image: mysql:5.7
    restart: always
    ports:
      - "3307:3307"
    command: --disable-partition-engine-check
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./db/data/mysql:/var/lib/mysql
    networks:
      - backend
networks:
  backend:
