-- MySQL Script generated by MySQL Workbench
-- Thu Jan 17 15:52:19 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema cliovis
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `cliovis` ;

-- -----------------------------------------------------
-- Schema cliovis
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cliovis` DEFAULT CHARACTER SET utf8 ;
USE `cliovis` ;

-- -----------------------------------------------------
-- Table `cliovis`.`project`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cliovis`.`project` ;

CREATE TABLE IF NOT EXISTS `cliovis`.`project` (
  `project_id` INT NOT NULL AUTO_INCREMENT,
  `project_name` VARCHAR(45) NULL,
  `description` VARCHAR(100) NULL,
  PRIMARY KEY (`project_id`),
  UNIQUE INDEX `project_name_UNIQUE` (`project_name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cliovis`.`study`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cliovis`.`study` ;

CREATE TABLE IF NOT EXISTS `cliovis`.`study` (
  `study_id` INT NOT NULL AUTO_INCREMENT,
  `study_name` VARCHAR(45) NULL,
  `description` VARCHAR(100) NULL,
  `project_id` INT NOT NULL,
  PRIMARY KEY (`study_id`),
  UNIQUE INDEX `study_name_UNIQUE` (`study_name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cliovis`.`subject`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cliovis`.`subject` ;

CREATE TABLE IF NOT EXISTS `cliovis`.`subject` (
  `subject_id` INT NOT NULL AUTO_INCREMENT,
  `sex` CHAR(10) NULL,
  `race` VARCHAR(45) NULL,
  `birth_date` DATE NULL,
  `study_id` INT NOT NULL,
  `subject_num` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`subject_id`),
  UNIQUE INDEX `subject_num_UNIQUE` (`subject_num` ASC, `study_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cliovis`.`subject_visit`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cliovis`.`subject_visit` ;

CREATE TABLE IF NOT EXISTS `cliovis`.`subject_visit` (
  `visit_id` INT NOT NULL AUTO_INCREMENT,
  `visit_event` VARCHAR(45) NULL,
  `visit_num` INT NULL,
  `disease_status` VARCHAR(45) NULL,
  `event_date` DATE NULL,
  `subject_id` INT NOT NULL,
  PRIMARY KEY (`visit_id`),
  UNIQUE INDEX `visit_num_UNIQUE` (`visit_num` ASC, `subject_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cliovis`.`observations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cliovis`.`observations` ;

CREATE TABLE IF NOT EXISTS `cliovis`.`observations` (
  `observation_id` INT NOT NULL AUTO_INCREMENT,
  `item` VARCHAR(45) NOT NULL,
  `value` VARCHAR(45) NULL,
  `category` VARCHAR(45) NULL,
  `scale` VARCHAR(45) NOT NULL,
  `subject_visit_id` INT NOT NULL,
  `item_type` VARCHAR(45) NULL,
  PRIMARY KEY (`observation_id`),
  UNIQUE INDEX `subject_visit_id_UNIQUE` (`subject_visit_id` ASC, `item` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
